name: hive_app
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  hive: ^2.2.1
  html: ^0.15.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3

